TOOL_CATALOG = [
    {"slug":"nmap", "name":"Nmap", "category":"network", "mode":"active-safe", "description":"Découverte contrôlée de services sur les actifs autorisés.", "executable":"nmap", "safety_boundary":"TCP connect/service detection; no NSE/evasion", "default_enabled":True},
    {"slug":"nuclei", "name":"Nuclei", "category":"web", "mode":"restricted", "description":"Contrôles d'exposition et de mauvaise configuration non intrusifs.", "executable":"nuclei", "safety_boundary":"info/low/medium; intrusive/exploit families excluded", "default_enabled":True},
    {"slug":"zap", "name":"OWASP ZAP", "category":"web", "mode":"baseline-plan", "description":"DAST baseline/passive assessment compatible CI.", "executable":"zap-baseline.py", "safety_boundary":"baseline/passive only through integrated plan", "default_enabled":True},
    {"slug":"semgrep", "name":"Semgrep", "category":"code", "mode":"local", "description":"SAST pour analyser les chemins de code et anti-patterns.", "executable":"semgrep", "safety_boundary":"local source tree only", "default_enabled":True},
    {"slug":"trivy", "name":"Trivy", "category":"supply-chain", "mode":"local", "description":"Vulnérabilités, misconfiguration et secrets dans des artefacts locaux.", "executable":"trivy", "safety_boundary":"local filesystem/container inputs", "default_enabled":True},
    {"slug":"gitleaks", "name":"Gitleaks", "category":"secrets", "mode":"local", "description":"Détection de secrets avec redaction des valeurs.", "executable":"gitleaks", "safety_boundary":"local repository only; redact output", "default_enabled":True},
    {"slug":"john", "name":"John the Ripper", "category":"credentials", "mode":"offline-only", "description":"Audit de hashes fournis dans le coffre de labo.", "executable":"john", "safety_boundary":"offline hash files only; explicit feature flag", "default_enabled":False},
    {"slug":"hashcat", "name":"Hashcat", "category":"credentials", "mode":"offline-plan", "description":"Capacité de vérification de hash disponible sur une station dédiée.", "executable":"hashcat", "safety_boundary":"not launched by web API; local dedicated station", "default_enabled":False},
    {"slug":"hydra", "name":"THC Hydra", "category":"authentication", "mode":"readiness-only", "description":"Préparation d'un test d'authentification réseau et garde-fous.", "executable":"hydra", "safety_boundary":"no network credential attempts from platform", "default_enabled":False},
    {"slug":"sqlmap", "name":"sqlmap", "category":"injection", "mode":"readiness-only", "description":"Cadrage d'un test d'injection à exécuter sur une station de pentest isolée.", "executable":"sqlmap", "safety_boundary":"no automated exploitation from platform", "default_enabled":False},
]
