"""SOC Initial Migration"""
import uuid
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [("organizations","0001_initial"), ("threat_intel","0001_initial")]
    operations = [
        migrations.CreateModel(name="DetectionRule", fields=[
            ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True)),
            ("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),
            ("updated_at",models.DateTimeField(auto_now=True)),
            ("name",models.CharField(max_length=255)),
            ("rule_type",models.CharField(max_length=20)),
            ("description",models.TextField(blank=True)),
            ("content",models.TextField()),
            ("severity",models.CharField(max_length=10,default="medium")),
            ("status",models.CharField(max_length=20,default="active")),
            ("mitre_tactics",models.JSONField(default=list,blank=True)),
            ("mitre_techniques",models.JSONField(default=list,blank=True)),
            ("tags",models.JSONField(default=list,blank=True)),
            ("false_positive_rate",models.FloatField(default=0.0)),
            ("hit_count",models.IntegerField(default=0)),
            ("author",models.CharField(max_length=255,blank=True)),
            ("references",models.JSONField(default=list,blank=True)),
            ("is_african_specific",models.BooleanField(default=False)),
        ], options={"ordering":["-severity","name"]}),
        migrations.CreateModel(name="Alert", fields=[
            ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True)),
            ("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),
            ("updated_at",models.DateTimeField(auto_now=True)),
            ("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="alerts",to="organizations.organization")),
            ("rule",models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,related_name="alerts",to="soc.detectionrule")),
            ("title",models.CharField(max_length=500)),
            ("description",models.TextField()),
            ("severity",models.CharField(max_length=10,db_index=True)),
            ("status",models.CharField(max_length=20,default="new",db_index=True)),
            ("source",models.CharField(max_length=20)),
            ("raw_log",models.JSONField(default=dict)),
            ("enriched_data",models.JSONField(default=dict)),
            ("src_ip",models.GenericIPAddressField(null=True,blank=True,db_index=True)),
            ("dst_ip",models.GenericIPAddressField(null=True,blank=True)),
            ("src_port",models.IntegerField(null=True,blank=True)),
            ("dst_port",models.IntegerField(null=True,blank=True)),
            ("protocol",models.CharField(max_length=20,blank=True)),
            ("hostname",models.CharField(max_length=255,blank=True)),
            ("related_iocs",models.ManyToManyField(blank=True,related_name="alerts",to="threat_intel.ioc")),
            ("mitre_tactics",models.JSONField(default=list,blank=True)),
            ("mitre_techniques",models.JSONField(default=list,blank=True)),
            ("assigned_to",models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,related_name="assigned_alerts",to="organizations.user")),
            ("acknowledged_at",models.DateTimeField(null=True,blank=True)),
            ("acknowledged_by",models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,related_name="acknowledged_alerts",to="organizations.user")),
            ("resolved_at",models.DateTimeField(null=True,blank=True)),
            ("tags",models.JSONField(default=list,blank=True)),
            ("notes",models.TextField(blank=True)),
        ], options={"ordering":["-created_at"]}),
        migrations.AddIndex(model_name="alert",index=models.Index(fields=["organization","status","severity"],name="alert_org_status_sev")),
        migrations.CreateModel(name="Incident", fields=[
            ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True)),
            ("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),
            ("updated_at",models.DateTimeField(auto_now=True)),
            ("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="incidents",to="organizations.organization")),
            ("title",models.CharField(max_length=500)),
            ("description",models.TextField()),
            ("incident_type",models.CharField(max_length=30,default="unknown")),
            ("severity",models.CharField(max_length=10,db_index=True)),
            ("status",models.CharField(max_length=20,default="open",db_index=True)),
            ("alerts",models.ManyToManyField(blank=True,related_name="incidents",to="soc.alert")),
            ("related_iocs",models.ManyToManyField(blank=True,to="threat_intel.ioc")),
            ("affected_assets",models.ManyToManyField(blank=True,to="organizations.asset")),
            ("assigned_to",models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,related_name="assigned_incidents",to="organizations.user")),
            ("responders",models.ManyToManyField(blank=True,related_name="incident_responses",to="organizations.user")),
            ("detected_at",models.DateTimeField()),
            ("contained_at",models.DateTimeField(null=True,blank=True)),
            ("resolved_at",models.DateTimeField(null=True,blank=True)),
            ("mitre_tactics",models.JSONField(default=list,blank=True)),
            ("mitre_techniques",models.JSONField(default=list,blank=True)),
            ("systems_affected",models.IntegerField(default=0)),
            ("data_compromised",models.BooleanField(default=False)),
            ("financial_impact_usd",models.DecimalField(max_digits=15,decimal_places=2,null=True,blank=True)),
            ("executive_summary",models.TextField(blank=True)),
            ("root_cause",models.TextField(blank=True)),
            ("lessons_learned",models.TextField(blank=True)),
            ("remediation_steps",models.JSONField(default=list,blank=True)),
            ("tags",models.JSONField(default=list,blank=True)),
            ("is_public",models.BooleanField(default=False)),
            ("tlp_level",models.CharField(max_length=10,default="amber")),
        ], options={"ordering":["-detected_at"]}),
        migrations.CreateModel(name="IncidentTimeline", fields=[
            ("id",models.BigAutoField(primary_key=True)),
            ("incident",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="timeline",to="soc.incident")),
            ("timestamp",models.DateTimeField(db_index=True)),
            ("author",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to="organizations.user")),
            ("action",models.CharField(max_length=255)),
            ("details",models.TextField(blank=True)),
            ("evidence",models.JSONField(default=dict,blank=True)),
            ("is_automated",models.BooleanField(default=False)),
        ], options={"ordering":["timestamp"]}),
    ]
