play.http.secret.key = "africanwatch-thehive-secret-change-in-production"
play.http.context = "/"
play.server.http.port = 9000
db.janusgraph {
  storage.backend = berkeleyje
  storage.directory = /opt/thp/thehive/db
  index.search.backend = lucene
  index.search.directory = /opt/thp/thehive/index
}
storage {
  provider = localfs
  localfs.location = /opt/thp/thehive/files
}
auth { providers = [{name = local}] }
