"use client";
import { useEffect, useState } from "react";
import { Radar, Search, ShieldAlert, RefreshCw } from "lucide-react";
import api from "@/lib/api";
export default function IntelligencePage(){
  const [kind,setKind]=useState("domain"),[value,setValue]=useState(""),[data,setData]=useState<any>(null),[forecasts,setForecasts]=useState<any[]>([]),[campaigns,setCampaigns]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function lookup(){if(!value.trim())return;setBusy(true);setError("");try{const r=await api.intelligence.passiveLookup(kind,value);setData(r.data)}catch(e:any){setError(e?.response?.data?.error||"Lookup refusé ou indisponible.")}finally{setBusy(false)}}
  async function loadForecasts(){try{const r=await api.intelligence.forecasts({ordering:"-generated_at"});setForecasts(r.data?.results||[])}catch{}}
  async function refreshForecasts(){try{await api.intelligence.refreshForecasts();await loadForecasts()}catch{}}
  async function loadCampaigns(){try{const r=await api.intelligence.campaignRadar();setCampaigns(r.data||[])}catch{}}
  useEffect(()=>{loadForecasts();loadCampaigns()},[]);
  return <div className="p-6 space-y-6"><div className="flex items-center justify-between"><div><div className="text-cyan-400 text-[10px] tracking-[0.35em] uppercase">Intelligence Center</div><h1 className="text-2xl font-semibold text-white mt-1">Passive Recon & Threat Intelligence</h1><p className="text-gray-500 text-sm mt-2">Preuves publiques, enrichissement passif, corrélation et signaux de tendance.</p></div><Radar className="w-8 h-8 text-cyan-400"/></div>
    <div className="grid lg:grid-cols-3 gap-4"><section className="lg:col-span-2 rounded-sm border border-cyan-900/40 bg-[#091425] p-5"><div className="flex items-center gap-2 text-white font-medium"><Search className="w-4 h-4 text-cyan-400"/>Lookup passif</div><div className="flex flex-col md:flex-row gap-2 mt-4"><select value={kind} onChange={e=>setKind(e.target.value)} className="bg-[#060d1a] border border-cyan-900/50 rounded-sm px-3 py-2 text-sm text-gray-300"><option value="domain">Domaine</option><option value="ip">IP</option></select><input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")lookup()}} placeholder="example.org ou 203.0.113.10" className="flex-1 bg-[#060d1a] border border-cyan-900/50 rounded-sm px-3 py-2 text-sm text-white outline-none"/><button onClick={lookup} disabled={busy} className="px-4 py-2 bg-cyan-500/15 border border-cyan-500/30 text-cyan-300 rounded-sm text-sm">{busy?"Analyse…":"Enrichir"}</button></div>{error&&<div className="mt-4 text-sm text-red-300">{error}</div>}{data&&<pre className="mt-4 max-h-[440px] overflow-auto text-xs text-gray-300 bg-[#050a13] border border-gray-900 rounded-sm p-4">{JSON.stringify(data,null,2)}</pre>}</section>
      <section className="rounded-sm border border-cyan-900/40 bg-[#091425] p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-white font-medium"><ShieldAlert className="w-4 h-4 text-amber-300"/>Forecast</div><button onClick={refreshForecasts}><RefreshCw className="w-4 h-4 text-gray-500 hover:text-cyan-300"/></button></div><div className="mt-4 space-y-3">{forecasts.length?forecasts.slice(0,6).map((f:any)=><div key={f.id} className="border border-gray-800 bg-[#060d1a] p-3"><div className="text-xs text-cyan-300 uppercase tracking-widest">{f.signal_type}</div><div className="text-sm text-white mt-1">{f.level} · score {Math.round((f.score||0)*100)}%</div><div className="text-[11px] text-gray-500 mt-1">confiance {Math.round((f.confidence||0)*100)}%</div></div>):<div className="text-sm text-gray-500">Pas encore assez de signaux.</div>}</div></section></div>
    <section className="rounded-sm border border-cyan-900/40 bg-[#091425] p-5"><div className="text-white font-medium">Campaign / Signal Radar</div><div className="text-xs text-gray-500 mt-1">Corrélation défensive sur 7 jours, par IOC et langue. Ce module ne réalise aucune attribution politique.</div><div className="mt-4 grid md:grid-cols-2 lg:grid-cols-4 gap-3">{campaigns.slice(0,12).map((c:any)=><div key={c.key} className="border border-gray-800 bg-[#060d1a] p-3"><div className="text-xs text-cyan-300 truncate">{c.key}</div><div className="text-sm text-white mt-1">{c.observations} observations</div><div className="text-[11px] text-gray-500 mt-1">{c.languages?.join(", ")||"—"} · {c.cross_language?"multi-lang":"single-lang"}</div></div>)}{!campaigns.length&&<div className="text-sm text-gray-500">Pas encore assez de corrélations.</div>}</div></section>
    <div className="grid md:grid-cols-3 gap-4">{[["Public Web","Actualités, RSS, RDAP, DNS, Certificate Transparency, APIs publiques"],["Onion Research","Sources .onion explicitement autorisées via Tor, collecte passive"],["Evidence","SHA-256, provenance, fraîcheur, corroboration et TLP"]].map(([t,d])=><div key={t} className="rounded-sm border border-cyan-900/30 bg-[#091425] p-4"><div className="text-sm text-white">{t}</div><div className="text-xs text-gray-500 mt-2">{d}</div></div>)}</div>
  </div>
}
