"""Threat Intel Initial Migration"""
import uuid
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [("organizations","0001_initial")]
    operations = [
        migrations.CreateModel(name="ThreatFeed", fields=[
            ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True)),
            ("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),
            ("updated_at",models.DateTimeField(auto_now=True)),
            ("name",models.CharField(max_length=255)),
            ("description",models.TextField(blank=True)),
            ("feed_type",models.CharField(max_length=20)),
            ("url",models.URLField()),
            ("api_key",models.CharField(max_length=255,blank=True)),
            ("api_key_header",models.CharField(max_length=100,default="X-API-Key")),
            ("is_public",models.BooleanField(default=True)),
            ("is_african_specific",models.BooleanField(default=False)),
            ("fetch_frequency_hours",models.IntegerField(default=6)),
            ("last_fetched_at",models.DateTimeField(null=True,blank=True)),
            ("last_ioc_count",models.IntegerField(default=0)),
            ("total_iocs_imported",models.IntegerField(default=0)),
            ("status",models.CharField(max_length=20,default="pending")),
            ("last_error",models.TextField(blank=True)),
            ("tlp_level",models.CharField(max_length=10,default="white")),
            ("tags",models.JSONField(default=list,blank=True)),
        ], options={"ordering":["name"]}),
        migrations.CreateModel(name="ThreatActor", fields=[
            ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True)),
            ("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),
            ("updated_at",models.DateTimeField(auto_now=True)),
            ("name",models.CharField(max_length=255,unique=True)),
            ("aliases",models.JSONField(default=list,blank=True)),
            ("description",models.TextField(blank=True)),
            ("motivation",models.CharField(max_length=20,default="unknown")),
            ("sophistication",models.CharField(max_length=20,default="intermediate")),
            ("country_of_origin",models.CharField(max_length=3,blank=True)),
            ("targets_africa",models.BooleanField(default=False,db_index=True)),
            ("target_countries",models.JSONField(default=list,blank=True)),
            ("target_sectors",models.JSONField(default=list,blank=True)),
            ("known_tools",models.JSONField(default=list,blank=True)),
            ("known_techniques",models.JSONField(default=list,blank=True)),
            ("first_seen",models.DateField(null=True,blank=True)),
            ("last_activity",models.DateField(null=True,blank=True)),
            ("is_active",models.BooleanField(default=True)),
            ("references",models.JSONField(default=list,blank=True)),
        ], options={"ordering":["-last_activity"]}),
        migrations.CreateModel(name="IOC", fields=[
            ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True)),
            ("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),
            ("updated_at",models.DateTimeField(auto_now=True)),
            ("ioc_type",models.CharField(max_length=20,db_index=True)),
            ("value",models.CharField(max_length=2048,db_index=True)),
            ("value_normalized",models.CharField(max_length=2048,db_index=True)),
            ("severity",models.CharField(max_length=10,default="medium",db_index=True)),
            ("confidence",models.IntegerField(default=50)),
            ("tlp_level",models.CharField(max_length=10,default="green")),
            ("feed",models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,related_name="iocs",to="threat_intel.threatfeed")),
            ("source_organization",models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,related_name="submitted_iocs",to="organizations.organization")),
            ("source_reference",models.URLField(blank=True)),
            ("reporter_name",models.CharField(max_length=255,blank=True)),
            ("is_african_threat",models.BooleanField(default=False,db_index=True)),
            ("african_countries_targeted",models.JSONField(default=list,blank=True)),
            ("first_seen",models.DateTimeField(db_index=True)),
            ("last_seen",models.DateTimeField(db_index=True)),
            ("expiry_date",models.DateTimeField(null=True,blank=True)),
            ("is_active",models.BooleanField(default=True,db_index=True)),
            ("description",models.TextField(blank=True)),
            ("tags",models.JSONField(default=list,blank=True)),
            ("malware_families",models.JSONField(default=list,blank=True)),
            ("attack_patterns",models.JSONField(default=list,blank=True)),
            ("country_code",models.CharField(max_length=3,blank=True,db_index=True)),
            ("country_name",models.CharField(max_length=100,blank=True)),
            ("asn",models.CharField(max_length=20,blank=True)),
            ("asn_name",models.CharField(max_length=255,blank=True)),
            ("latitude",models.FloatField(null=True,blank=True)),
            ("longitude",models.FloatField(null=True,blank=True)),
            ("mitre_tactics",models.JSONField(default=list,blank=True)),
            ("mitre_techniques",models.JSONField(default=list,blank=True)),
            ("hit_count",models.IntegerField(default=0)),
            ("false_positive_count",models.IntegerField(default=0)),
            ("raw_data",models.JSONField(default=dict,blank=True)),
        ], options={"ordering":["-last_seen","-confidence"]}),
        migrations.AlterUniqueTogether(name="ioc",unique_together={("ioc_type","value_normalized")}),
        migrations.AddIndex(model_name="ioc",index=models.Index(fields=["ioc_type","severity"],name="ioc_type_sev")),
        migrations.AddIndex(model_name="ioc",index=models.Index(fields=["is_active","is_african_threat"],name="ioc_active_african")),
        migrations.CreateModel(name="Campaign", fields=[
            ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True)),
            ("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),
            ("updated_at",models.DateTimeField(auto_now=True)),
            ("name",models.CharField(max_length=255)),
            ("description",models.TextField()),
            ("threat_actor",models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,related_name="campaigns",to="threat_intel.threatactor")),
            ("start_date",models.DateField(null=True,blank=True)),
            ("end_date",models.DateField(null=True,blank=True)),
            ("is_ongoing",models.BooleanField(default=True)),
            ("target_countries",models.JSONField(default=list,blank=True)),
            ("target_sectors",models.JSONField(default=list,blank=True)),
            ("iocs",models.ManyToManyField(blank=True,related_name="campaigns",to="threat_intel.ioc")),
            ("mitre_tactics",models.JSONField(default=list,blank=True)),
            ("mitre_techniques",models.JSONField(default=list,blank=True)),
            ("severity",models.CharField(max_length=10,default="high")),
            ("references",models.JSONField(default=list,blank=True)),
            ("tlp_level",models.CharField(max_length=10,default="green")),
        ], options={"ordering":["-start_date"]}),
        migrations.AddField(model_name="threatactor",name="iocs",
            field=models.ManyToManyField(blank=True,related_name="threat_actors",to="threat_intel.ioc")),
        migrations.CreateModel(name="ThreatReport", fields=[
            ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True)),
            ("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),
            ("updated_at",models.DateTimeField(auto_now=True)),
            ("title",models.CharField(max_length=500)),
            ("report_type",models.CharField(max_length=20)),
            ("summary",models.TextField()),
            ("content",models.TextField()),
            ("author",models.CharField(max_length=255,blank=True)),
            ("organization",models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,to="organizations.organization")),
            ("published_at",models.DateTimeField(null=True,blank=True)),
            ("is_public",models.BooleanField(default=False)),
            ("tlp_level",models.CharField(max_length=10,default="green")),
            ("campaigns",models.ManyToManyField(blank=True,to="threat_intel.campaign")),
            ("iocs",models.ManyToManyField(blank=True,to="threat_intel.ioc")),
            ("tags",models.JSONField(default=list,blank=True)),
            ("pdf_file",models.FileField(blank=True,null=True,upload_to="reports/")),
        ], options={"ordering":["-published_at"]}),
    ]
